version: "3.8"
services:
  db:
    env_file:
      - db.env
    image: crossfold/hub-db:1.4.2
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: "exit 0"
  redis:
    image: redis:6.2.5-alpine
    ports:
      - "6379:6379"
  server:
    env_file:
      - web-server.env
    image: crossfold/web-server:v1.13.0.onprem
    environment:
      - DATABASE_HUBDB_HOST=db
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
    ports: 
      - "8080:8080"
  client:
    env_file:
      - web-client.env
    image: crossfold/web-client:v1.13.11.onprem
    volumes:
      - "./web-client.js:/app/public/env.js"
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "80:3000"
