version: '3.8'
services:
  db:
    env_file:
      - db.env
    image: crossfold/hub-db:1.4.1
    ports:
      - '5432:5432'
    volumes:
      - './pgdata:/var/lib/postgresql/data'
  redis:
    image: redis:6.2.5-alpine
    ports:
      - '6379:6379'
  server:
    env_file:
      - web-server.env
    image: crossfold/web-server:1.10.4
    environment:
      - DATABASE_HUBDB_HOST=db
  client:
    env_file:
      - web-client.env
    image: crossfold/web-client:1.11.1
